### ISSUE TITLE
Dependency Task Arrows feature?

### ISSUE THREAD

**Issue by dmk23** [pmeisen/js-gantt#1]
I am considering moving to this package from the Google's Gannt Chart largely because of the ability to fully customize the tooltips and the axes.

However I am not seeing the ability to add dependency arrows connecting the tasks or customize their appearance like this is possible with Google Charts:
https://developers.google.com/chart/interactive/docs/gallery/ganttchart#styling-arrows

Are you planning or considering to add this functionality?

**Comment by pmeisen** [comment]
Hi dmk23, 

thanks for your message. Currently I'm not planning to add any functionality like that to the current implementation. That said, feel free to implement the feature yourself, the implementation is pretty self explaining and it should be easy to add another view between the actual tasks and the chart (which may contain the dependencies) and the full code is available on GitHub!
