### ISSUE TITLE
Support question - Usage with node.js

### ISSUE THREAD

**Issue by ORESoftware** [pmeisen/js-gantt#2]
I was looking at this package for creating an svg gantt chart

https://github.com/substack/gantt-chart

the problem is that it's very limited, and I don't want to visualize dependencies, I just want to show a timeline of various processes, when they start and stop. So I am looking to just provide this info:

```js
const chart = {
   process1: {
     displayName: 'foo',
     start: number,
     end:  number,
   },

    process2: {
     displayName: 'bar',
     start: number,
     end:  number,
   },

    process3: {
     displayName: 'baz',
     start: number,
     end:  number,
   }
};
```
**so my question is:**
is there a way I can write the `<svg></svg>` data to a file using this package? 
I want to use it with Node.js, not in the browser, and write the html to an .html file.

thanks!

**Comment by pmeisen** [comment]
Hi,

I added an example on how you could utilize the library within nodeJs and create SVG files. The example utilizes phantomJS and is just an example on how it could be done.

https://github.com/pmeisen/js-gantt/tree/master/examples
https://github.com/pmeisen/js-gantt/blob/master/examples/exportSvgWithNodeJs/example.js

Hope that helps.

**Comment by ORESoftware** [comment]
nice, I may try it out. I got the Google Chart API to work, but it's really annoying because it doesn't work with data that is more granular than days (it can't handle hours, minutes, seconds, milliseconds, which sucks).

Any help with these issues, appreciated:

https://github.com/google/google-visualization-issues/issues/2515
https://github.com/GoogleWebComponents/google-chart/issues/194

I thought you might want to know about those limitations, because then your lib can fill in the gaps?

**Comment by pmeisen** [comment]
Thanks I have a look at these limitations, I cannot help you to solve the mentioned issues, because I'm no working with these libraries (at least when I comes to intervals). Nevertheless, I'll have a look and keep you updated if I find something.
