### ISSUE TITLE
Looks great but

### ISSUE THREAD

**Issue by jalle007** [pmeisen/js-gantt#3]
can I set the label for the tasks ?
I need them to be displayed on the left of the chart

**Comment by jalle007** [comment]
@pmeisen 

can you please help me to setup basic chart like this
![image](https://user-images.githubusercontent.com/2169100/31913369-5112c2fa-b847-11e7-896b-6a4128ecf346.png)

**Comment by pmeisen** [comment]
Hi jalle007,

thanks for the enhancement request. I hope you found a way on how to add this to the current implementation. If so, I would be more then happy to see a push from you and add it to this open source project.
